export type JudgeItem = {
  id: string;
  section: "season" | "game";
  who: string;
  fact: string;
  note?: string;
};

/** Unique season fact types. Keep or skip. */
export const SEASON_STATS: JudgeItem[] = [
  {
    id: "S1",
    section: "season",
    who: "Schwarber",
    fact: "45 HR, MLB lead",
  },
  {
    id: "S2",
    section: "season",
    who: "Olson",
    fact: ".253/.325/.509, 40 HR, 88 RBI",
    note: "Harris is 14 back in HR.",
  },
  {
    id: "S3",
    section: "season",
    who: "Crow-Armstrong",
    fact: "44 HR and 37 SB this season",
    note: "Only Cubs player in a 30-30 season.",
  },
  {
    id: "S4",
    section: "season",
    who: "Abrams",
    fact: "First 30-30 season of his career",
    note: "30 HR, 30 SB.",
  },
  {
    id: "S5",
    section: "season",
    who: "Crow-Armstrong",
    fact: "Most home runs of his career",
    note: "44 this year. 31 in 2025.",
  },
  {
    id: "S6",
    section: "season",
    who: "Olson",
    fact: "40 HR, 2nd-most of his career",
    note: "54 in 2023.",
  },
  {
    id: "S7",
    section: "season",
    who: "Alvarez",
    fact: "First 40-home run season of his career",
    note: "37 in 2022.",
  },
  {
    id: "S8",
    section: "season",
    who: "Ohtani",
    fact: "Career-best 1.79 ERA",
    note: "2.33 in 2022.",
  },
  {
    id: "S9",
    section: "season",
    who: "Ohtani",
    fact: "30 HR and 85.2 IP, 95 K",
  },
  {
    id: "S10",
    section: "season",
    who: "Alvarez",
    fact: "MLB-best OPS 1.031",
    note: ".312/.431/.600.",
  },
  {
    id: "S11",
    section: "season",
    who: "Crow-Armstrong",
    fact: "13 more HR than last year",
    note: "31 in 2025.",
  },
  {
    id: "S12",
    section: "season",
    who: "Alvarez",
    fact: "Home OPS 1.180",
    note: "23 of 40 HR at home.",
  },
  {
    id: "S13",
    section: "season",
    who: "Alvarez",
    fact: "30 HR vs right-handers",
    note: "OPS 1.104 vs RHP.",
  },
  {
    id: "S14",
    section: "season",
    who: "Caminero",
    fact: "Hit in 15 straight games",
    note: "Aug 17 to Sep 1.",
  },
  {
    id: "S15",
    section: "season",
    who: "Crow-Armstrong",
    fact: "7 multi-homer games this season",
    note: "Last: Sep 16 vs Braves.",
  },
  {
    id: "S16",
    section: "season",
    who: "Misiorowski",
    fact: "1.89 ERA, 0.81 WHIP in 166.1 IP",
    note: "243 K.",
  },
  {
    id: "S17",
    section: "season",
    who: "Misiorowski",
    fact: "First 200-strikeout season of his career",
    note: "87 in 2025.",
  },
  {
    id: "S18",
    section: "season",
    who: "Arraez",
    fact: ".313, MLB batting lead",
    note: "180 hits.",
  },
  {
    id: "S19",
    section: "season",
    who: "Miller",
    fact: "37 SV, 1.12 ERA",
    note: "119 K in 64.1 IP.",
  },
  {
    id: "S20",
    section: "season",
    who: "Carroll",
    fact: "16 triples, MLB lead",
  },
  {
    id: "S21",
    section: "season",
    who: "Simpson",
    fact: "45 SB, MLB lead",
  },
  {
    id: "S22",
    section: "season",
    who: "Caminero",
    fact: "41 HR",
    note: "2nd straight 40-HR season.",
  },
  {
    id: "S23",
    section: "season",
    who: "Alvarez",
    fact: "105 BB, MLB lead",
    note: ".431 OBP.",
  },
  {
    id: "S24",
    section: "season",
    who: "Burleson",
    fact: "111 RBI, MLB lead",
  },
  {
    id: "S25",
    section: "season",
    who: "Harris",
    fact: "26 HR, 2nd on the Braves",
    note: "Olson is 14 ahead.",
  },
];

/** Unique single-game fact types. Keep or skip. */
export const GAME_STATS: JudgeItem[] = [
  {
    id: "G1",
    section: "game",
    who: "Crow-Armstrong",
    fact: "Hit for the cycle vs Rockies",
    note: "First in the last two seasons.",
  },
  {
    id: "G2",
    section: "game",
    who: "Tatis",
    fact: "5 hits vs Rockies",
    note: "5-5, Jul 28.",
  },
  {
    id: "G3",
    section: "game",
    who: "Crow-Armstrong",
    fact: "3 home runs vs Reds",
    note: "4-6, 6 RBI, Aug 29.",
  },
  {
    id: "G4",
    section: "game",
    who: "Tatis",
    fact: "2 home runs vs Twins",
    note: "4-5, Aug 23.",
  },
  {
    id: "G5",
    section: "game",
    who: "Crow-Armstrong",
    fact: "4 hits and a steal @ Pirates",
    note: "Jul 25.",
  },
  {
    id: "G6",
    section: "game",
    who: "Witt",
    fact: "3 hits and a steal @ Nationals",
    note: "Jun 16.",
  },
  {
    id: "G7",
    section: "game",
    who: "Misiorowski",
    fact: "9 IP, 0 ER, 15 K vs Phillies",
    note: "Jun 12.",
  },
  {
    id: "G8",
    section: "game",
    who: "Sale",
    fact: "9 IP, 0 ER, 11 K vs Dodgers",
    note: "Aug 27.",
  },
  {
    id: "G9",
    section: "game",
    who: "Schlittler",
    fact: "6 IP, 0 ER, 13 K vs Reds",
    note: "Jun 19.",
  },
  {
    id: "G10",
    section: "game",
    who: "Soto",
    fact: "Only Mets home run vs Phillies",
    note: "3-5 | HR, 2B, Sep 18.",
  },
  {
    id: "G11",
    section: "game",
    who: "Simpson",
    fact: "Only Rays steal vs Red Sox",
    note: "0-5, Sep 18.",
  },
  {
    id: "G12",
    section: "game",
    who: "Olson",
    fact: "Tied with Harris for the Braves hit lead",
    note: "Both 3 hits, Sep 18.",
  },
  {
    id: "G13",
    section: "game",
    who: "Jenkins",
    fact: "Team-high 3 hits @ Angels",
    note: "3-4 | HR, Sep 18.",
  },
  {
    id: "G14",
    section: "game",
    who: "Olson",
    fact: "HR @ Astros",
    note: "First since Sep 13.",
  },
  {
    id: "G15",
    section: "game",
    who: "Crow-Armstrong",
    fact: "2 HR vs Braves",
    note: "First since Aug 17.",
  },
  {
    id: "G16",
    section: "game",
    who: "Riley",
    fact: "First 0-for-4 in the last two weeks",
    note: "Sep 18 @ Astros.",
  },
  {
    id: "G17",
    section: "game",
    who: "Crow-Armstrong",
    fact: "2 HR and a triple vs Braves",
    note: "3-4, Sep 16.",
  },
  {
    id: "G18",
    section: "game",
    who: "Baldwin",
    fact: "5-5, 2 HR vs Rangers",
    note: "Jul 19.",
  },
  {
    id: "G19",
    section: "game",
    who: "Raleigh",
    fact: "3-3, 3 HR vs Phillies",
    note: "Aug 24.",
  },
  {
    id: "G20",
    section: "game",
    who: "Ohtani",
    fact: "6 IP, 10 K vs Mets",
    note: "Apr 15.",
  },
  {
    id: "G21",
    section: "game",
    who: "Acuña",
    fact: "2 HR and 2 SB @ Reds",
    note: "May 30.",
  },
  {
    id: "G22",
    section: "game",
    who: "Yastrzemski",
    fact: "0-for-4, 2 K @ Astros",
    note: "Last multi-hit Sep 11.",
  },
  {
    id: "G23",
    section: "game",
    who: "Yastrzemski",
    fact: "Last HR Sep 14 @ Cubs",
  },
  {
    id: "G24",
    section: "game",
    who: "Schlittler",
    fact: "7.1 IP, 0 ER, 12 K, 0 BB @ Phillies",
    note: "Jul 24.",
  },
  {
    id: "G25",
    section: "game",
    who: "Iglesias",
    fact: "1 IP, 0 ER, 3 K @ Astros",
    note: "Sep 18.",
  },
];

export const JUDGE_ITEMS: JudgeItem[] = [...SEASON_STATS, ...GAME_STATS];
